project:
  type: book

book:
  title: "Advanced Data Computing (405 @ LU) Notes"
  author: "Abhishek Chakraborty"
  date: "7/24/2026"
  reader-mode: true
  
  page-footer:
    left: |
      Advanced Data Computing (405) Course Notes by Abhishek Chakraborty.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    
    - part: SQL
      chapters: 
        - sql_1.qmd
        - sql_2.qmd
        - sql_3.qmd
        - sql_4.qmd
        
    - part: Text Analysis
      chapters: 
        - TextAnalysis_1.qmd
        - TextAnalysis_2.qmd
        - TextAnalysis_3.qmd
        
    - part: Geospatial Data
      chapters: 
        - GeospatialData.qmd
        
    - part: Code Performance
      chapters: 
        - CodePerformance.qmd
        
    - part: R Package
      chapters: 
        - Rpackage.qmd    
        
        
        
#    - intro.qmd
#    - summary.qmd
#    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



